// Generated by CoffeeScript 1.7.1
(function() {
  var util;

  util = require("util");

  exports.imageForm = function(req, res) {
    res.render("upload", {
      title: "Upload Images"
    });
  };

  exports.uploadImage = function(req, res, next) {
    var pathArray;
    console.log("file info: ", req.files.image);
    pathArray = req.files.image.path.split("/");
    res.send(util.format(" Task Complete \n uploaded %s (%d Kb) to %s", req.files.image.name, req.files.image.size / 1024 | 0, req.files.image.path, req.body.title, "<img src=\"images/" + pathArray[pathArray.length - 1] + "\">"));
  };

}).call(this);

//# sourceMappingURL=common.map
