// Generated by CoffeeScript 1.7.1
(function() {
  var list, util;

  util = require("util");

  list = [];

  exports.imageForm = function(req, res) {
    res.render("upload", {
      list: list
    });
  };

  exports.uploadImage = function(req, res, next) {
    var modidied, now, object, pathArray;
    if (req.files.image.size !== 0) {
      console.log("request info: ", req);
      pathArray = req.files.image.path.split("/");
      now = new Date();
      modidied = now.getDate() + '/' + (now.getMonth() + 1) + '/' + now.getFullYear() + ' ' + now.getHours() + ':' + now.getMinutes();
      object = {
        path: "images/" + pathArray[pathArray.length - 1],
        title: req.body.title,
        size: req.files.image.size / 1024 | 0,
        modified: modidied
      };
      list.push(object);
    }
    res.render("upload", {
      list: list
    });
  };

}).call(this);

//# sourceMappingURL=common.map
